### ISSUE TITLE
Problem important spatial files with ^M ending

### ISSUE THREAD

**Issue by rittman** [RittmanResearch/maybrain#5]
This might be an issue for people who generate their spatial information files in windows and some mac programmes. The brainObj.importSpatialInfo function can't manage files with line breaks ^M

**Comment by rittman** [comment]
Code to possibly include:
 f = io.open(fname,"r", encoding='utf-16-le')

**Comment by tjiagoM** [comment]
I might have possibly corrected this. Can you test @rittman and, if it's not working, do you have any of those files created in windows which I can try?
