### ISSUE TITLE
Invoking allen.py

### ISSUE THREAD

**Issue by ghost** [RittmanResearch/maybrain#7]
Hi,

could you direct me on how to invoke allen.py trying to match the allen data to a parcellation different from the one Dr. Whitaker used in her papers.

**Comment by xuqiang9042** [comment]
Did you resovle this question?I have the same question as you.

**Comment by rittman** [comment]
Hi Xuqiang,

I will copy at reply from one of my colleagues to Moosa:

"Say you are using a different parcellation with N=324 parcels, you need to do the following:

"You need to write a script such as the one in the attached example which calls allen.py (note that the example below actually calls a modified version “allen_2015_10_13” - you can ignore this - some of that code will not be relevant to you, it’s just an example).

"The way things are currently implemented in Maybrain you also need to create a folder (I have called it “AT324” in this example) and put in it a txt file containing an adjacency matrix which is 324x324. The contents of this matrix only matter if you use additional Maybrain functions. If you just want to do the matching the weights in the adjacency matrix can be random. In my example this file is called “Adj_324.txt”.

Most importantly you need to provide a new “spatialFile” containing the N centroids of your parcellation. In this example the spatialFile is called “atlas324_ROI_mni.txt” (note that allen.py has a default spatialFile, which is what you are replacing). This is the only input Maybrain actually needs to match the allen data to your parcellation."

The relevant attached code is in the pdf below.

Kind regards,

Tim

[getMatrices_2015_10_13.py-1.pdf](https://github.com/rittman/maybrain/files/755780/getMatrices_2015_10_13.py-1.pdf)

**Comment by moosahmed** [comment]
Attaching a instructions file I made for invoking allen.py for a different parcellation.

Thanks,
Moosa

**Comment by rittman** [comment]
Many thanks Moosa, that's very helpful.

Regards,

Tim

On 06/02/17 22:52, moosahmed wrote:
Attaching a instructions file I made for invoking allen.py for a different parcellation.

Thanks,
Moosa
